sonar.projectKey=duyler_config
sonar.organization=duyler
sonar.projectName=Config
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**
sonar.issue.ignore.multicriteria=e1

# Configuration files need to be reloadable, require is correct here
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S3334
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php
