<?php

declare(strict_types=1);

namespace Duyler\tests;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class TestConfigFactory extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[Test]
    public function with_file_provider(): void
    {

    }
}
